### ISSUE TITLE
Need to fix PDF viewing on calendar tab

### ISSUE THREAD

**Issue by cfrankovich** [cypressbayhs/cypressbayhs.github.io#2]
It is huge! It's also really ugly and can use some work. Maybe I'll just change this to an image in the future...

**Comment by DanyPalma** [comment]
fixed in [Pull Request #5 ](https://github.com/cypressbayhs/cypressbayhs.github.io/pull/5)

please review and let me know if i should add or change anything 

😺

**Comment by cfrankovich** [comment]
Fixed in pull request #5
